### ISSUE TITLE
这个包能支持 cos 的元数据加速桶吗

### ISSUE THREAD

**Issue by Smith-Cruise** [tencentyun/hadoop-cos#123]
我就单纯的引入 `hadoop-cos`，不引入其他 jar 包，能完美支持 cos 元数据加速桶吗。

**Comment by yuyang733** [comment]
不行的，还需要一个 chdfs-network-plugin 的jar包。这个依赖了。

**Comment by Smith-Cruise** [comment]
就是我还要额外放一个 `chdfs-network-plugin.jar`  包把

**Comment by yuyang733** [comment]
> 就是我还要额外放一个 `chdfs-network-plugin.jar` 包把

是的，需要额外放置一个chdfs-network-plugin 的jar包。因为这个依赖在pom文件里面只是编译scope。运行期间需要在classpath中查找。
