### ISSUE TITLE
在location设置为cosn地址时，进行插入数据会报错

### ISSUE THREAD

**Issue by hccnm** [tencentyun/hadoop-cos#130]
**Describe the bug**
在trino-427版本中使用cos 8.3.0 版本，进行插入数据操作时会抛异常，hadoop版本2.7.5

![image](https://github.com/tencentyun/hadoop-cos/assets/45889323/bdbefb50-2757-4a08-a4c0-83171c2c1ae6)

![image](https://github.com/tencentyun/hadoop-cos/assets/45889323/bcee40f1-260d-4d8d-b5af-c684ce931566)

**Comment by yuyang733** [comment]
> **Describe the bug** 在trino-427版本中使用cos 8.3.0 版本，进行插入数据操作时会抛异常，hadoop版本2.7.5
> 
> ![image](https://private-user-images.githubusercontent.com/45889323/290796334-bdbefb50-2757-4a08-a4c0-83171c2c1ae6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2NjQ1NDUsIm5iZiI6MTcwMjY2NDI0NSwicGF0aCI6Ii80NTg4OTMyMy8yOTA3OTYzMzQtYmRiZWZiNTAtMjc1Ny00YTA4LWE0YzAtODMxNzFjMmMxYWU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE1VDE4MTcyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjZjgxMGYxZDgwN2RmNDVmZDBiNzEwNTlkMzNhOTNjMzIwZjkzMmVkY2Y1ZDQ1ODkzZjMwN2U5ZTJhZGI2MzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.L5Bq3qBgJ8u3JVIKp6L4jd465GGdXTbHaZJlcZHzKyc)
> 
> ![image](https://private-user-images.githubusercontent.com/45889323/290795585-bcee40f1-260d-4d8d-b5af-c684ce931566.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2NjQ1NDUsIm5iZiI6MTcwMjY2NDI0NSwicGF0aCI6Ii80NTg4OTMyMy8yOTA3OTU1ODUtYmNlZTQwZjEtMjYwZC00ZDhkLWI1YWYtYzY4NGNlOTMxNTY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE1VDE4MTcyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQwYjFmMTg1Yzc2YjQzN2NiNjUwZDRkMmU5YTYxNmNiOTRjYTViYzdlZjhiNjU1ZjQ5N2I0NDlkYjM0YzAxYWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BKAFhsJlZRMo1jYHKui_eGwP8WDPemIzVTA3ia5i9qw)

感谢反馈，我认为这个是因为 commons-io 这个包的版本冲突导致的。hadoop-cos 中需要依赖 commons-io-2.4/2.5 的包。您可以检查一下，你的 Trino 环境中是否依赖了其他版本的 commons-io 包或者是缺少了这个依赖。其实这个包在 Hadoop 的 CLASSPATH 中是有的。比如你可以在 ${HADOOP_HOME}/share/hadoop/common/lib 中找到。

**Comment by hccnm** [comment]
感谢回复，添加完jar包后顺利进入到下一个流程，不过发现了新的问题，
![image](https://github.com/tencentyun/hadoop-cos/assets/45889323/90f671c9-ca2f-4501-848f-24a7eb754700)
![image](https://github.com/tencentyun/hadoop-cos/assets/45889323/71872546-7cee-472e-8190-0d19f183600c)
在trino的运行环境中，它的jdk版本是大于9的，会触发java的模块引用限制，导致发生异常，这个有更好的解决方案吗？

**Comment by yuyang733** [comment]
> 感谢回复，添加完jar包后顺利进入到下一个流程，不过发现了新的问题，
> 
> ![image](https://github.com/tencentyun/hadoop-cos/assets/45889323/90f671c9-ca2f-4501-848f-24a7eb754700)
> 
> ![image](https://github.com/tencentyun/hadoop-cos/assets/45889323/71872546-7cee-472e-8190-0d19f183600c)
> 
> 在trino的运行环境中，它的jdk版本是大于9的，会触发java的模块引用限制，导致发生异常，这个有更好的解决方案吗？

这里确实不支持JDK 8以上的版本。

**Comment by hccnm** [comment]
> > 感谢回复，添加完jar包后顺利进入到下一个流程，不过发现了新的问题，
> > ![image](https://private-user-images.githubusercontent.com/45889323/290965042-90f671c9-ca2f-4501-848f-24a7eb754700.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI3MDY5MjgsIm5iZiI6MTcwMjcwNjYyOCwicGF0aCI6Ii80NTg4OTMyMy8yOTA5NjUwNDItOTBmNjcxYzktY2EyZi00NTAxLTg0OGYtMjRhN2ViNzU0NzAwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE2VDA2MDM0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmOWI1YjQxZGY0ZjYzMjkzMzcyM2MxY2JhMWMyOGE5YzcwMmM0MTExZTljN2YyOTU0ZGY2NmIyNzFjZjRiODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.co2Y5vCvdPHUYp-xtRzgsv4_B7uGbgeZMp2o26AZ2SU)
> > ![image](https://private-user-images.githubusercontent.com/45889323/290965043-71872546-7cee-472e-8190-0d19f183600c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI3MDY5MjgsIm5iZiI6MTcwMjcwNjYyOCwicGF0aCI6Ii80NTg4OTMyMy8yOTA5NjUwNDMtNzE4NzI1NDYtN2NlZS00NzJlLTgxOTAtMGQxOWYxODM2MDBjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE2VDA2MDM0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExNzAzYmEyYjAzYzE0MmU2M2I1NmE1MjFhYjBmZjUwNmFiOWFkMzVlYzc4MmYxMzliNzJmZTVhZTAyZDEyN2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kMHQxfuoAQSpVEldmptAqeUAuuqFt6IP9viSY9lzz3M)
> > 在trino的运行环境中，它的jdk版本是大于9的，会触发java的模块引用限制，导致发生异常，这个有更好的解决方案吗？
> 
> 这里确实不支持JDK 8以上的版本。

我在在jvm.config中设置了，--add-opens=java.base/sun.nio.ch=ALL-UNNAMED。临时解决这个问题了

**Comment by yuyang733** [comment]
这个雨

> UNNAMED
 很好，


> > > 感谢回复，添加完jar包后顺利进入到下一个流程，不过发现了新的问题，
> > > ![image](https://private-user-images.githubusercontent.com/45889323/290965042-90f671c9-ca2f-4501-848f-24a7eb754700.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI3MDY5MjgsIm5iZiI6MTcwMjcwNjYyOCwicGF0aCI6Ii80NTg4OTMyMy8yOTA5NjUwNDItOTBmNjcxYzktY2EyZi00NTAxLTg0OGYtMjRhN2ViNzU0NzAwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE2VDA2MDM0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmOWI1YjQxZGY0ZjYzMjkzMzcyM2MxY2JhMWMyOGE5YzcwMmM0MTExZTljN2YyOTU0ZGY2NmIyNzFjZjRiODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.co2Y5vCvdPHUYp-xtRzgsv4_B7uGbgeZMp2o26AZ2SU)
> > > ![image](https://private-user-images.githubusercontent.com/45889323/290965043-71872546-7cee-472e-8190-0d19f183600c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI3MDY5MjgsIm5iZiI6MTcwMjcwNjYyOCwicGF0aCI6Ii80NTg4OTMyMy8yOTA5NjUwNDMtNzE4NzI1NDYtN2NlZS00NzJlLTgxOTAtMGQxOWYxODM2MDBjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE2VDA2MDM0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExNzAzYmEyYjAzYzE0MmU2M2I1NmE1MjFhYjBmZjUwNmFiOWFkMzVlYzc4MmYxMzliNzJmZTVhZTAyZDEyN2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kMHQxfuoAQSpVEldmptAqeUAuuqFt6IP9viSY9lzz3M)
> > > 在trino的运行环境中，它的jdk版本是大于9的，会触发java的模块引用限制，导致发生异常，这个有更好的解决方案吗？
> > 
> > 
> > 这里确实不支持JDK 8以上的版本。
> 
> 我在在jvm.config中设置了，--add-opens=java.base/sun.nio.ch=ALL-UNNAMED。临时解决这个问题了

这种解决方案也是可以的。 只是 hadoop 生态很多组件其实对 JDK 9 及以后的版本其实都未兼容。
