### ISSUE TITLE
为何需要重启node manager

### ISSUE THREAD

**Issue by LazWorm** [tencentyun/hadoop-cos#142]

**Comment by LazWorm** [comment]
从文档来看，cos distcp以及hadoop cos相关的包都是放在hadoop客户端的，distcp应该是由客户端发起，为何需要重启node manager，重启node manager会影响到客户端加载jar包吗？还是说我的理解出错了？谢谢

**Comment by yuyang733** [comment]
原则上应该是不需要重启 NM 的，只是避免某些情况，hadoop-cos 的相关依赖包没有加载到 NM 进程的 classpath 中的情况。
