### ISSUE TITLE
java.lang.NoClassDefFoundError: org/apache/hadoop/fs/cosn/CRC64Checksum

### ISSUE THREAD

**Issue by 736008081** [tencentyun/hadoop-cos#143]
命令：hadoop jar cos-distcp-1.13-3.1.0.jar -libjars cos_api-bundle-5.6.137.2.jar,hadoop-cos-3.2.2-8.3.8.jar -Dfs.cosn.credentials.provider=org.apache.hadoop.fs.auth.SimpleCredentialProvider -Dfs.cosn.impl=org.apache.hadoop.fs.CosFileSystem -Dfs.AbstractFileSystem.cosn.impl=org.apache.hadoop.fs.CosN --src hdfs://test1 --dest hdfs://test2 --skipMode none --checkMode none 
![image](https://github.com/tencentyun/hadoop-cos/assets/7286106/4ecaf8f6-5bf3-40f1-9c56-1baf06d3a100)

**Comment by yuyang733** [comment]
@abyswang 是关于cos-distcp的，看看。

**Comment by abyswang** [comment]
![image](https://github.com/tencentyun/hadoop-cos/assets/94839856/72236fec-05c3-436b-af1d-4379101d85de)

按照这个方式排查一下 find 一下能不能查到 -libjars 指定的jar 看一下版本 以及是否在hadoop classpath 下面 能否被加载
