### ISSUE TITLE
org.apache.hadoop.fs.PartialListing NoSuchMethodError

### ISSUE THREAD

**Issue by xiatiansong** [tencentyun/hadoop-cos#18]
hadoop version:3.1.1
run distcp cmd: sudo -u hdfs hadoop distcp hdfs://xxx/ks3/ods_spider  cosn://xxx/
error info:
Error: org.apache.hadoop.fs.PartialListing.<init>(Ljava/lang/String;[Lorg/apache/hadoop/fs/FileMetadata;[Lorg/apache/hadoop/fs/FileMetadata;)V
20/09/28 11:28:26 INFO mapreduce.Job: Task Id : attempt_1601263446127_0001_m_000004_0, Status : FAILED

最后发现是org.apache.hadoop.fs.PartialListing被hadoop common本身的同名的类覆盖，建议重命名该类或者上面新加一个包名(与cos在hadoop cloud storage的一致， https://github.com/apache/hadoop/blob/82ff7bc9abc8f3ad549db898953d98ef142ab02d/hadoop-cloud-storage-project/hadoop-cos/src/main/java/org/apache/hadoop/fs/cosn/PartialListing.java)

**Comment by yuyang733** [comment]
> hadoop version:3.1.1
> run distcp cmd: sudo -u hdfs hadoop distcp hdfs://xxx/ks3/ods_spider cosn://xxx/
> error info:
> Error: org.apache.hadoop.fs.PartialListing.(Ljava/lang/String;[Lorg/apache/hadoop/fs/FileMetadata;[Lorg/apache/hadoop/fs/FileMetadata;)V
> 20/09/28 11:28:26 INFO mapreduce.Job: Task Id : attempt_1601263446127_0001_m_000004_0, Status : FAILED
> 
> 最后发现是org.apache.hadoop.fs.PartialListing被hadoop common本身的同名的类覆盖，建议重命名该类或者上面新加一个包名(与cos在hadoop cloud storage的一致， https://github.com/apache/hadoop/blob/82ff7bc9abc8f3ad549db898953d98ef142ab02d/hadoop-cloud-storage-project/hadoop-cos/src/main/java/org/apache/hadoop/fs/cosn/PartialListing.java)

感谢反馈。 这里你的环境里面依赖了3.3.0的common么？

因为common里面partialListing是hadoop 3.3.0的版本里面引入的。而hadoop 3.3.0的话，hadoop-cos已经提交了社区，并且partialListing在cosn这个包下面了。

**Comment by xiatiansong** [comment]
抱歉，集群使用的是CDH版本，还以为CDH版本前面的大版本和apache的是一致，结果搜索CDH集群的 hadoop-common-3.1.1.7.1.3.0-100.jar 包才发现有这个类 org.apache.hadoop.fs.PartialListing，大概已经使用了最新的版本。

#Wed Aug 05 10:50:21 UTC 2020
version=3.1.1.7.1.3.0-100
groupId=org.apache.hadoop
artifactId=hadoop-common

**Comment by yuyang733** [comment]
> 抱歉，集群使用的是CDH版本，还以为CDH版本前面的大版本和apache的是一致，结果搜索CDH集群的 hadoop-common-3.1.1.7.1.3.0-100.jar 包才发现有这个类 org.apache.hadoop.fs.PartialListing，大概已经使用了最新的版本。CDH集群版本中未搜索到apache hadoop cos包。
> 
> #Wed Aug 05 10:50:21 UTC 2020
> version=3.1.1.7.1.3.0-100
> groupId=org.apache.hadoop
> artifactId=hadoop-common

就是，你看可否自行fork一下，然后rename一下这个包以兼容一下你的环境。

我们也在考虑做一下此类case的兼容，不过因为需要走评估和发版流程，会有一个时间窗口。

**Comment by yuyang733** [comment]
@xiatiansong 你好，就是我们这边也发布了CDH集成COS相关的文章，您可以看一下。

[CDH 配置 Hadoop-COS 指引](https://cloud.tencent.com/document/product/436/47063)
