### ISSUE TITLE
CosN的上传文件的时间戳是不是没有和HDFS的表现得一致？导致出现问题？

### ISSUE THREAD

**Issue by shangwen** [tencentyun/hadoop-cos#3]
我基于你们的配置出现了异常：
```
2019-04-15 14:45:47,683 DEBUG org.apache.hadoop.security.UserGroupInformation: PrivilegedActionException as:hadoop (auth:SIMPLE) cause:java.io.IOException: Resource cosn://xxx-xxx/user/hadoop/.flink/application_1555078596113_0014/logback.xml changed on src filesystem (expected 1555259286000, was 1555310742000
```
我们提交flinnk作业的时候，可以看出时间戳不一致导致下载资源文件报错
原因分析
对比YARN的代码，是对比资源时间戳和文件在COS的时间戳导致报错：
文件：FSDownload.java
```
  private Path copy(Path sCopy, Path dstdir) throws IOException {
    FileSystem sourceFs = sCopy.getFileSystem(conf);
    Path dCopy = new Path(dstdir, "tmp_"+sCopy.getName());
    FileStatus sStat = sourceFs.getFileStatus(sCopy);
    if (sStat.getModificationTime() != resource.getTimestamp()) {
      throw new IOException("Resource " + sCopy +
          " changed on src filesystem (expected " + resource.getTimestamp() +
          ", was " + sStat.getModificationTime());
    }
    if (resource.getVisibility() == LocalResourceVisibility.PUBLIC) {
      if (!isPublic(sourceFs, sCopy, sStat, statCache)) {
        throw new IOException("Resource " + sCopy +
            " is not publicly accessable and as such cannot be part of the" +
            " public cache.");
      }
    }

    FileUtil.copy(sourceFs, sStat, FileSystem.getLocal(conf), dCopy, false,
        true, conf);
    return dCopy;
  }
```
而flink构造resource的时候，用的是文件的本地时间戳
![image](https://user-images.githubusercontent.com/4383034/56115536-2d39b300-5f96-11e9-9afb-e7885d1a8eca.png)
但我发现cos用的是上传的时间，而不是改文件本地修改的最后时间
```
-rw-rw-rw-   1 hadoop hadoop       2331 2019-04-15 15:14 /user/hadoop/.flink/application_1555078596113_0017/logback.xml
```
本地文件的时间为：
```
-rwxrwxrwx 1 root users 2331 Apr 15 00:28 ./conf/logback.xml
```
所以一直报错expected 1555259286000，即00:28的时间和文件系统不匹配，如果换成hdfs就是正常的logback.xml的时间，所以，这里的时间的表现形式是不是和hdfs不一致呢？并不是完全兼容hdfs的行为？

**Comment by yuyang733** [comment]
> 我基于你们的配置出现了异常：
> 
> ```
> 2019-04-15 14:45:47,683 DEBUG org.apache.hadoop.security.UserGroupInformation: PrivilegedActionException as:hadoop (auth:SIMPLE) cause:java.io.IOException: Resource cosn://xxx-xxx/user/hadoop/.flink/application_1555078596113_0014/logback.xml changed on src filesystem (expected 1555259286000, was 1555310742000
> ```
> 我们提交flinnk作业的时候，可以看出时间戳不一致导致下载资源文件报错
> 原因分析
> 对比YARN的代码，是对比资源时间戳和文件在COS的时间戳导致报错：
> 文件：FSDownload.java
> 
> ```
>   private Path copy(Path sCopy, Path dstdir) throws IOException {
>     FileSystem sourceFs = sCopy.getFileSystem(conf);
>     Path dCopy = new Path(dstdir, "tmp_"+sCopy.getName());
>     FileStatus sStat = sourceFs.getFileStatus(sCopy);
>     if (sStat.getModificationTime() != resource.getTimestamp()) {
>       throw new IOException("Resource " + sCopy +
>           " changed on src filesystem (expected " + resource.getTimestamp() +
>           ", was " + sStat.getModificationTime());
>     }
>     if (resource.getVisibility() == LocalResourceVisibility.PUBLIC) {
>       if (!isPublic(sourceFs, sCopy, sStat, statCache)) {
>         throw new IOException("Resource " + sCopy +
>             " is not publicly accessable and as such cannot be part of the" +
>             " public cache.");
>       }
>     }
> 
>     FileUtil.copy(sourceFs, sStat, FileSystem.getLocal(conf), dCopy, false,
>         true, conf);
>     return dCopy;
>   }
> ```
> 而flink构造resource的时候，用的是文件的本地时间戳
> ![image](https://user-images.githubusercontent.com/4383034/56115536-2d39b300-5f96-11e9-9afb-e7885d1a8eca.png)
> 但我发现cos用的是上传的时间，而不是改文件本地修改的最后时间
> 
> ```
> -rw-rw-rw-   1 hadoop hadoop       2331 2019-04-15 15:14 /user/hadoop/.flink/application_1555078596113_0017/logback.xml
> ```
> 本地文件的时间为：
> 
> ```
> -rwxrwxrwx 1 root users 2331 Apr 15 00:28 ./conf/logback.xml
> ```
> 所以一直报错expected 1555259286000，即00:28的时间和文件系统不匹配，如果换成hdfs就是正常的logback.xml的时间，所以，这里的时间的表现形式是不是和hdfs不一致呢？并不是完全兼容hdfs的行为？

这个不能支持，所有的mtime时间均取落盘时间。 S3、OSS等都是这样做的。

**Comment by shangwen** [comment]
经过和COS技术支持沟通，对象存储不支持时间settime包括oss和s3，暂时关闭
